const CONFLICT_SCORE_MIN = 0;
const CONFLICT_SCORE_MAX = 100;
const CONFLICT_SCORE_DECAY_PER_MINUTE = 0.5;
const CONFLICT_WINDOW_MS = 60_000;
const CONFLICT_GENERAL_ATTACK_SCORE = 4;
const CONFLICT_DIRECT_ATTACK_SCORE = 8;
const CONFLICT_REPEATED_ATTACK_SCORE = 10;
const CONFLICT_MUTUAL_ATTACK_SCORE = 15;
const CONFLICT_DEESCALATION_SCORE = 5;

module.exports = {
  CONFLICT_SCORE_MIN,
  CONFLICT_SCORE_MAX,
  CONFLICT_SCORE_DECAY_PER_MINUTE,
  CONFLICT_WINDOW_MS,
  CONFLICT_GENERAL_ATTACK_SCORE,
  CONFLICT_DIRECT_ATTACK_SCORE,
  CONFLICT_REPEATED_ATTACK_SCORE,
  CONFLICT_MUTUAL_ATTACK_SCORE,
  CONFLICT_DEESCALATION_SCORE,
};
