const CONFLICT_SCORE_MIN = 0;
const CONFLICT_SCORE_MAX = 100;
const CONFLICT_SCORE_DECAY_PER_MINUTE = 0.5;

module.exports = {
  CONFLICT_SCORE_MIN,
  CONFLICT_SCORE_MAX,
  CONFLICT_SCORE_DECAY_PER_MINUTE,
};
